### PR TITLE
Update cli.py

### PR DESCRIPTION
**Pull request by juur**
readfp is not available in Python 3.12.

### CODE REVIEW

**Comment by mattrobenolt** [comment]
So I see this was added in python 3.2: https://docs.python.org/3/library/configparser.html#configparser.ConfigParser.read_file

So that's fine, but I assume this is going to break the 2.7 path, which uses the older library where there is no alternative:

https://python.readthedocs.io/en/v2.7.2/library/configparser.html#ConfigParser.RawConfigParser.readfp

So I think there are a few ways we can solve this to maintain compatibility.

**Comment by juur** [comment]
Unsure how that will work as in python3.12+ jinja2-cli doesn't work at all, so you may need something more complicated if you want to continue to support python 2.7 (which is quite old)

**Comment by juur** [comment]
Seemed to work OK in my local test ...

**Comment by juur** [comment]
Any plans to do a PyPI release, so this is available?

**Comment by juur** [comment]
@mattrobenolt ?

**Pull request merged**
