### PR TITLE
Support for recursively replacing variables

### PR DESCRIPTION
**Pull request by pravindahal**
Please see example in tests.

I am not convinced this is the correct way to go about it though.

### CODE REVIEW

**Comment by mattrobenolt** [comment]
What's the usecase for this? I get what it's doing, I just can't think of why I'd want to use this.

**Comment by pravindahal** [comment]
I was trying to use the tool on [this template](https://github.com/jlund/streisand/blob/master/playbooks/roles/openconnect/templates/ocserv-init.j2) using [this yml](https://github.com/jlund/streisand/blob/master/playbooks/roles/openconnect/vars/main.yml) which didn't work as expected. This is an [ansible template](https://docs.ansible.com/ansible/template_module.html) which uses Jinja2 with support for recursive evaluation.

**Comment by mattrobenolt** [comment]
I'm going to probably pull this in later. Do you have a preference on it being a CLI argument? To be, it seems like we could just allow this behavior all the time. I don't see any real cases where this would cause an issue unexpectedly.

**Comment by afeblot** [comment]
I'd vote to have it available all the time, i.e. directly integrated in the jinja lib. I've had to implement a similar thing in a python script of mine, whereas I could have just added a recursive=True param to the template.render() call if this had been available.

**Comment by hvtuananh** [comment]
Hi all, any chance we could merge this?

**Comment by rosstex** [comment]
Bump, this would be great

**Pull request closed without merging**
